# SITE CONFIGURATION
title: Avatao # your site title
author: Avatao # You :P
description: > # Meta description of Homepage
  Avatao blog about IT security and Appsec trainings. Avatao teaches people how to build secure software from design to deployment. 
  Avatao covers the entire SDLC including topics like secure coding in Python, Java, C#, web security, OWASP top 10, Testing, Code review and DevSecOps.
baseurl: "" # the subpath of your site, e.g. /blog
host: "0.0.0.0"
url: "https://blog.avatao.com/" # the base hostname & protocol for your site, e.g. http://example.com

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/avatao/avatao.github.io/master/images/avataobloglogo.png

authors:
  mark:
    name: Márk Félegyházi    
    linkedin: felegyhazi
    twitter: markfelegyhazi
    web: https://hu.linkedin.com/in/felegyhazi  
  gabor:
    name: Gábor Pék  
    linkedin: gaborpek
    twitter: gaborpek
    web: https://www.linkedin.com/in/gaborpek/
  noname:
    name: Gábor Pék
    linkedin: gaborpek
    twitter: gaborpek
    web: https://www.linkedin.com/in/gaborpek/
  akos:
    name: Ákos Hajba    
    linkedin: 
    twitter: 
    web: 
  marton:
    name: Márton Németh
    linkedin: 
    twitter: 
    web: 

# SEO PLUGIN
social:
  name: Avatao
  links:
    - https://twitter.com/theavatao
    - https://www.facebook.com/theavatao
    - https://www.linkedin.com/company/theavatao
    - https://github.com/avatao

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Benefits', link: 'https://avatao.com/#Benefits'}
  - {name: 'Solutions', link: 'https://avatao.com/#Solutions'}
  - {name: 'Why us?', link: 'https://avatao.com/#WhyUs'}
  - {name: 'Impact', link: 'https://avatao.com/#Impact'}
  - {name: 'Blog', link: '/'}

#tagline: >
  #Learn to build secure software

hero_img: posts/avataoblogbg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: contact@avatao.com # email for form submission

twitter_username: theavatao # replace with your_twitter_username or comment to remove link from footer
facebook_username: theavatao
linkedin_username: company/theavatao
github_username: avatao

disqus:
  shortname: avataoblog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
